### ISSUE TITLE
Breakpoint on or directly after label is set to next line

### ISSUE THREAD

**Issue by fischerman** [ASMImproved/lea#63]
Every breakpoint that is set before line 11 breaks in line 12 although it should break in line 11

```
.data
hellostring:  .ascii "Hello "
              .asciiz "World!
"

.text
.globl main

main:
  li  $a0, 1
  la  $a1, hellostring    # line 12
  li  $a2, 14
  li  $v0, 4004
  syscall

  li  $a0, 0
  li  $v0, 4001
  syscall
```

**Comment by jangmarker** [comment]
waiting for http://stackoverflow.com/questions/37478266/gdbs-break-skips-line-on-break-at-label

**Comment by jangmarker** [comment]
update to that answer reveals `break *main` and `break *address` which works as expected

but for that to work we need the address of a location `main.s:7`
